import { createApp } from "@server/app/create-app.js";
import { expect, it } from "vitest";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { openTestDatabase } from "./database.js";
import { createUser } from "@core/modules/identity/passwords.js";
import { pluginServices } from "@core/shared/plugin-services.js";
import { createServerFilesCapability } from "@server/plugins/files-capability-adapter.js";

it("rechecks binding authorization and never changes the original file ACL", async () => {
  const db = await openTestDatabase({ driver: "sqlite", path: ":memory:" });
  const root = await mkdtemp(join(tmpdir(), "doca-binding-"));
  let app: Awaited<ReturnType<typeof createApp>> | undefined;
  try {
    const owner = await createUser(db, { login: "owner", displayName: "Owner", password: "test-password-2026" }, { bootstrap: true });
    const reader = await createUser(db, { login: "reader", displayName: "Reader", password: "test-password-2026" }, { actor: { ...owner, admin: 1 } });
    const files = createServerFilesCapability(db, { root, credentials: {}, endpointHosts: [], cdnKeyPairId: undefined, cdnPrivateKey: undefined });
    const context = { principalId: owner.id };
    const upload = await files.uploads.begin(context, { filename: "attachment.txt", mime: "text/plain", size: 5 });
    await files.uploads.write(context, { uploadId: upload.id, offset: 0, bytes: new TextEncoder().encode("hello") });
    await files.uploads.complete(context, { uploadId: upload.id });
    const file = await files.files.create(context, { uploadId: upload.id, folderId: null, name: "attachment.txt" });
    const binding = await files.bindings.bind(context, { fileId: file.id, owner: { ownerPlugin: "example.mail", ownerType: "mailbox", ownerId: "inbox", role: "attachment" } });
    const parallel = await Promise.all([1,2,3].map(() => files.bindings.bind(context,{fileId:file.id,owner:{ownerPlugin:"example.mail",ownerType:"mailbox",ownerId:"other",role:"attachment"}})));
    expect(new Set(parallel.map(row=>row.id)).size).toBe(1);
    const request = { principalId: reader.id };
    await expect(files.content.read!(request, { fileId: file.id })).rejects.toMatchObject({ status: 404 });
    await expect(files.content.read!(request, { fileId: file.id, bindingId: binding.id })).rejects.toMatchObject({ status: 404 });
    app = await createApp(db, { origin: "http://localhost:39130", storage: { root, credentials: {}, endpointHosts: [], cdnKeyPairId: undefined, cdnPrivateKey: undefined }, pluginDirectory: join(root, "plugins") });
    const login = await app.inject({ method: "POST", url: "/api/v1/auth/login", headers: { host: "localhost:39130", origin: "http://localhost:39130" }, payload: { login: "reader", password: "test-password-2026" } });
    const headers = { host: "localhost:39130", cookie: String(login.headers["set-cookie"]).split(";")[0]! };
    const url = `/api/v1/plugin-file-bindings/${binding.id}/content`;
    let allowed = true;
    pluginServices(db).permissions.set("example.mail.mailbox", { pluginId: "example.mail", resourceType: "mailbox", async authorize(id, resource, action) { return allowed && id === reader.id && resource === "inbox" && action === "file.read"; } });
    const read = await files.content.read!(request, { fileId: file.id, bindingId: binding.id });
    const chunks = []; for await (const chunk of read.body) chunks.push(Buffer.from(chunk));
    expect(Buffer.concat(chunks).toString()).toBe("hello");
    expect((await files.content.resolveDownload(request, { fileId: file.id, bindingId: binding.id })).href).toContain("/plugin-file-bindings/");
    await expect(files.content.read!(request, { fileId: file.id })).rejects.toMatchObject({ status: 404 });
    const download = await app.inject({ url, headers });
    expect(download.statusCode, download.body).toBe(200);
    expect(download.body).toBe("hello");
    allowed = false;
    expect((await app.inject({ url, headers })).statusCode).toBe(404);
    await expect(files.content.read!(request, { fileId: file.id, bindingId: binding.id })).rejects.toMatchObject({ status: 404 });
    pluginServices(db).permissions.clear();
    await expect(files.content.read!(request, { fileId: file.id, bindingId: binding.id })).rejects.toMatchObject({ status: 404 });
  } finally { await app?.close(); await db.destroy(); await rm(root, { recursive: true, force: true }); }
});
